//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkOrders()
        {
            this.Payments = new HashSet<Payments>();
        }
    
        public int work_order_id { get; set; }
        public Nullable<int> car_id { get; set; }
        public Nullable<int> mechanic_id { get; set; }
        public Nullable<int> service_id { get; set; }
        public System.DateTime work_order_date { get; set; }
        public Nullable<System.DateTime> completion_date { get; set; }
        public string status { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Mechanics Mechanics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
        public virtual Services Services { get; set; }
    }
}
